package common

import (
	mgo "gopkg.in/mgo.v2"
	bson "gopkg.in/mgo.v2/bson"
)

// NoticesSendStats is a MongoDB schema representation.
// The data is generated by aggregation scrips.
type NoticesSendStats struct {
	ID struct {
		Sender    string `bson:"sender"`
		Recipient string `bson:"recipient"`
	} `bson:"_id"`
	Notices uint `bson:"notices"`
}

// GetNoticesSendStats returns NoticesSendStats. The amount is specified by amount.
// Sorting is based on NoticesSendStats.Notices.
func GetNoticesSendStats(c *mgo.Collection, amount int, sortAsc bool) ([]NoticesSendStats, error) {
	sort := "notices"
	if !sortAsc {
		sort = "-" + sort
	}
	query := c.Find(bson.M{}).Sort(sort).Limit(amount)
	stats := []NoticesSendStats{}
	err := query.All(&stats)
	return stats, err
}
